name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Print versions
        run: |
          forge --version
          solc --version || true

      - name: Build
        run: forge build --sizes
        env:
          FOUNDRY_DISABLE_REMOTE_LOOKUPS: "1"

      - name: Test
        run: forge test -vvv
        env:
          FOUNDRY_DISABLE_REMOTE_LOOKUPS: "1"

